Fixed upload button -> /verify-certificate,  Fixed progressIndicatorPadding -> /progressIndicator
LlibertadApp/frontend pull request #10
Opened 2023-10-31 16:52 UTC by AlhuayOscar

2023-10-31 20:44 UTC, bonino97 approved these changes
Fijate q ttenes conflicts.

2023-10-31 20:44 UTC, bonino97 commented on src/pages/verify-certificate/verifyCertificate.tsx
> +      />
Actualizate la rama q creo q te quedo esto viejo.

2023-10-31 20:45 UTC, bonino97 requested changes

2023-10-31 20:45 UTC, bonino97 commented on src/pages/verify-certificate/verifyCertificate.tsx
> +      <FormHeader
Y creo q te esta dando Conflictos en el login tmb

2023-10-31 23:22 UTC, AlhuayOscar commented on src/pages/verify-certificate/verifyCertificate.tsx
> +      <FormHeader
Esta solucionadisimo ahora si! 👌

2023-10-31 23:22 UTC, AlhuayOscar commented
Listo!

2023-11-01 15:18 UTC, bonino97 approved these changes

2023-11-01 15:18 UTC, merged