Add timer to enable results for no auth users
LlibertadApp/frontend pull request #23
Opened 2023-11-02 04:03 UTC by fainstein

Se valida que se habiliten los resultados a partir del dia de la eleccion a las 19 hs, para los usuarios no autenticados

2023-11-02 04:19 UTC, bonino97 commented
@fainstein Que tarea del trello es esta?

2023-11-02 04:25 UTC, bonino97 requested changes

2023-11-02 04:25 UTC, bonino97 commented on src/hooks/utils/use-results-enabled.tsx
> +    }, 1000);
Jeff bezos se hace rico con esta funcion en el bucket de s3. Re-renderiza muchas veces. Si agregamos esta logica, sera desde el backend. Que seguramente se ataque cuando carguemos los resultados luego de las 9pm.

2023-11-02 10:09 UTC, bonino97 commented
@n3-n2-n1 algun comentario al respecto?

2023-11-02 10:57 UTC, bonino97 commented
@fainstein ahi vi la tarea, primero q nada gracias por tomarla, la validacion se hara luego, por ahora creo q lo q enfoca esa tarea es en hacer el nuevo login.

2023-11-03 02:43 UTC, agusvazquez commented on src/hooks/utils/use-results-enabled.tsx
> +  const resultsDate = new Date('2023-11-19T21:00:00-03:00');
Buenas! Dejo mi grano de arena, esto es super hackeable.

Idealmente estaria bueno que el API devuelva un boolean si esta habilitado o no, y meter esta logica en el backend.

2023-11-03 02:44 UTC, agusvazquez commented on src/pages/login/login.tsx
> +                  text: 'Los resultados estarán disponibles el 19/11/2023 a las 19:00 hs',
```suggestion
                  text: 'Los resultados estarán disponibles el 19/11/2023 a las 21:00 hs',
```

2023-11-03 02:59 UTC, fainstein commented on src/hooks/utils/use-results-enabled.tsx
> +  const resultsDate = new Date('2023-11-19T21:00:00-03:00');
Estoy de acuerdo. De aca para mi salen dos definiciones:

1. Deshabilitar el `Link` y proteger la `Route` desde el frontend, esto lo podemos sostener con la fecha del lado del cliente como propuse en este PR
2. Que el backend solo devuelva la informacion a partir de la hora definida el 19/11

2023-11-03 03:01 UTC, fainstein commented on src/hooks/utils/use-results-enabled.tsx
> +    }, 1000);
Entiendo, es razonable. Podemos actualizar en un intervalo mayor, o simplemente apelar a que los usuarios actualicen el sitio.
Sobre la validacion, puse mi vision en otro comment aca mismo 😄

2023-11-03 03:03 UTC, agusvazquez commented on src/hooks/utils/use-results-enabled.tsx
> +  const resultsDate = new Date('2023-11-19T21:00:00-03:00');
perfecto!

2023-11-03 03:08 UTC, agusvazquez commented on src/hooks/utils/use-results-enabled.tsx
> +    }, 1000);
Buenas, dejo un codigo que use en otro proyecto, no se lo vayan a chorear (guiño guiño).

Podes calcular el tiempo que falta entre la fecha actual y la fecha deseada (19 a las 9PM). Y no necesitas hacer un setInterval. 

Este ejemplo esta hecho usando DateTime (Luxon, https://www.npmjs.com/package/luxon)  

Espero que te sirva.

```
useEffect(() => {
    const now = DateTime.now();
    const {seconds: remainingSeconds} = dateTime.diff(now, 'seconds');
    const remainingMinutes = remainingSeconds / 60;

      setTimeout(
        () => XXXX,
        (remainingMinutes) * 60 * 1000,
      );
  }, [dateTime]);
```

2023-11-03 22:44 UTC, bonino97 commented
@fainstein gracias! esto, te lo cierro por q viene del back, un endpoint nos dira si estan o no habilitados. Se definio ayer con infra.

2023-11-03 22:44 UTC, closed without merging