card link modularization creation of view irregularities
LlibertadApp/frontend pull request #28
Opened 2023-11-02 06:23 UTC by luciano-repetti

Cree el componente card link para poder utilizarlo en home y en la vista irregularities:
![image](https://github.com/LlibertadApp/frontend/assets/67850074/4bdb0816-afd1-46b4-8261-700ff86be03b)

2023-11-02 10:07 UTC, bonino97 requested changes

2023-11-02 10:07 UTC, bonino97 commented on src/components/cardLink/index.tsx
> +  if (color === 'violet') {
aca se podria crear un enum

2023-11-02 10:07 UTC, bonino97 commented on src/components/cardLink/index.tsx
> +  let config;
type

2023-11-02 10:07 UTC, bonino97 commented on src/components/cardLink/index.tsx
> +  } else if(color === 'red') {
lo mismo, estaria bueno crear un enum

2023-11-02 10:07 UTC, bonino97 commented on src/pages/irregularities/irregularities.tsx
> +              link={'irregularities'}
agregale la barra adelante de irregularities por que puede pasar que al hacer click te detecte como que la ruta no es valida en produccion, con el '/irregularities' prevenis ese problema

2023-11-02 10:07 UTC, bonino97 commented on src/pages/irregularities/irregularities.tsx
> +              link={'irregularities'}
lo mismo

2023-11-02 10:07 UTC, bonino97 commented on src/pages/irregularities/irregularities.tsx
> +              link={'irregularities'}
lo mismo

2023-11-02 10:07 UTC, bonino97 commented on src/pages/irregularities/irregularities.tsx
> +              link={'irregularities'}
lo mismo

2023-11-02 17:25 UTC, luciano-repetti commented on src/pages/irregularities/irregularities.tsx
> +              link={'irregularities'}
Se le agrega automaticamente dentro del componente la barra, asi:

```
`/${link}`
```

2023-11-02 17:26 UTC, luciano-repetti commented on src/components/cardLink/index.tsx
> +  if (color === 'violet') {
Crear un enum para los colores que pueden existir?

2023-11-02 17:26 UTC, luciano-repetti commented on src/components/cardLink/index.tsx
> +  let config;
Type a que?

2023-11-03 22:14 UTC, bonino97 commented on src/components/cardLink/index.tsx
> +  let config;
@luciano-repetti al config.

2023-11-03 22:18 UTC, bonino97 commented on src/pages/irregularities/irregularities.tsx
> +              link={'irregularities'}
Queda mas descriptivo cuando es /irregularities

2023-11-03 22:18 UTC, bonino97 commented
@luciano-repetti corregite los conflicts (cambio la forma)

2023-11-03 22:21 UTC, bonino97 approved these changes

2023-11-03 22:21 UTC, merged