changes on upload data flow ui, add new tw colors
LlibertadApp/frontend pull request #59
Opened 2023-11-03 22:36 UTC by nbrusco

actualización y ajustes de ui de carga de datos

/UPLOAD-CERTIFICATE
![upload-certificate-1](https://github.com/LlibertadApp/frontend/assets/108240795/8273fb2a-82a7-4c83-8b9a-99c72fa57898)

/VERIFY-CERTIFICATE
![verify-certificate-1](https://github.com/LlibertadApp/frontend/assets/108240795/100ece88-773e-4e05-abc9-4d49edc4df51)

/LOAD-INFORMATION
![load-info-1](https://github.com/LlibertadApp/frontend/assets/108240795/6a1aa31f-af4d-48a9-9fb6-3f1a126b63be)
![total-results-2](https://github.com/LlibertadApp/frontend/assets/108240795/3400cec8-26d9-4d43-a7ba-0ec976a296f2)

2023-11-03 22:40 UTC, bonino97 commented
<img width="1255" alt="image" src="https://github.com/LlibertadApp/frontend/assets/24545141/f7d13f6e-d0a4-44b2-acca-40dc27241d86">

Nico, barbaro los cambios, fijate de pullearte dev de nuevo, por q se esta rompiendo el upload en desktop, yo le habia hecho unos fixes q quedaba alineado todo al medio

2023-11-03 22:41 UTC, nbrusco commented
chequeanding

2023-11-03 22:51 UTC, nbrusco commented
done @bonino97 

![image](https://github.com/LlibertadApp/frontend/assets/108240795/fd9866e5-c1d5-442c-86d8-e102f36a1223)

2023-11-03 23:21 UTC, bonino97 requested changes

2023-11-03 23:21 UTC, bonino97 commented on src/components/uploadImage/index.tsx
> +            className="flex flex-col items-center justify-centercursor-pointer mt-[30px] mb-10"
tenes las 2 props juntas -> justify-centercursor-pointer

2023-11-03 23:21 UTC, bonino97 commented on src/components/progressIndicator/styles.css
> +  height: 30px;
30px es = a 1.875rem, lo mejor es ir moviendo lo q este en px a rem por el tema mobile/desktop

https://nekocalc.com/es/px-a-rem-conversor

2023-11-04 02:16 UTC, nbrusco commented on src/components/progressIndicator/styles.css
> +  height: 30px;
Gracias Juan! done

2023-11-04 02:17 UTC, nbrusco reviewed
fix a comentarios

2023-11-04 02:17 UTC, nbrusco commented on src/components/uploadImage/index.tsx
> +            className="flex flex-col items-center justify-centercursor-pointer mt-[30px] mb-10"
Ready

2023-11-04 18:12 UTC, merged