protect /login route when auth token exists, fix overlay on scroll
LlibertadApp/frontend pull request #70
Opened 2023-11-05 07:49 UTC by nbrusco

- Creo middleware publicRoute, que verifica si el usuario está autenticado y si es así lo redirije /home
- Protejo /login

before
![Captura de pantalla 2023-11-05 043808](https://github.com/LlibertadApp/frontend/assets/108240795/63874a28-31a3-4446-b2f5-74acc9efabf0)

after
![Captura de pantalla 2023-11-05 043827](https://github.com/LlibertadApp/frontend/assets/108240795/a82833d7-fabd-4f55-8aea-63cec94e3014)

2023-11-05 14:36 UTC, NicooWolf commented
Revisa este PR, los cambios ya se habian hecho. https://github.com/LlibertadApp/frontend/pull/47

2023-11-05 16:44 UTC, NicooWolf requested changes
Posiblemente traiga conflictos con el PR https://github.com/LlibertadApp/frontend/pull/47 ya mergeado a la rama https://github.com/LlibertadApp/frontend/tree/jwt . 

@bonino97

2023-11-05 18:03 UTC, nbrusco commented
Más fixes a estilos:

![image](https://github.com/LlibertadApp/frontend/assets/108240795/86b7459a-a4eb-40c5-8444-3a4907704fb5)

![image](https://github.com/LlibertadApp/frontend/assets/108240795/6055ef7f-0830-4aa7-9bc4-f0e6978f5d3e)

2023-11-05 19:51 UTC, nbrusco commented
Luego de ajustar el padding faltaba ajustar la posición del svg del dropdown menu del menú hamburguesa

2023-11-06 13:35 UTC, nbrusco commented
se ajusta nuevamente styles del btn inferior del home para que esté en línea con el Figma, ahora con Phospor

2023-11-06 13:42 UTC, bonino97 approved these changes

2023-11-06 13:42 UTC, bonino97 commented on index.html
> +    <title>Libertapp</title>
Ponele -> LibertApp - SISTEMA ANTI FRAUDE ELECTORAL

2023-11-06 13:45 UTC, merged