Fix Login Error Validation Logic
LlibertadApp/frontend pull request #87
Opened 2023-11-06 20:44 UTC by AlhuayOscar

https://trello.com/c/PJWqccO4
Now
![image](https://github.com/LlibertadApp/frontend/assets/90626121/a60297e0-1669-4bd6-a32a-791e6aa54868)
Before
![image](https://github.com/LlibertadApp/frontend/assets/90626121/77329e6a-42a2-4ef1-832d-d41202738997)

2023-11-06 21:22 UTC, toro705 requested changes

2023-11-06 21:22 UTC, toro705 commented on src/pages/login/login.tsx
> +            !values.email.includes('@') ||
porque no movemos todas las validaciones a una variable, asi es mas legible?
O usar validator:
https://www.npmjs.com/package/validator

No me queda claro porque evaluamos que email sea valido para mostrar dos tipos diferentes de input de password. Si es para que se marque invalido si el email no se rellenó correctmente podemos buscarle una vuelta de tuerca diferente.
Guardar validaciones en estado, y  usarlas para comprobar y mostrar errores a travez de props, envez de renderizar dos componentes diferentes.
Si queres charlame cuando estes y nos reunimos

2023-11-06 21:28 UTC, bonino97 commented
@AlhuayOscar Oscar, consulta, esto lo resuelve yup, si te fijas en https://fraude-lla.netlify.app/login q todavia no esta merged tu rama, ya tiene estas validaciones que haces. Cual seria la nueva? La mejor solucion seria agregarle validaciones a Formik - Yup

2023-11-06 21:43 UTC, AlhuayOscar commented
El tema creo qué es la parte visual, como no encontrábamos la forma de evitar la doble validación en ambos campos aparecio una card dónde lo solucioné con React directamente

2023-11-06 23:11 UTC, AlhuayOscar commented
Cualquier cosa sí está solucionado en otro PR, o por Santiago, Desestimar este PR y cerrarlo sin dramas

2023-11-07 00:30 UTC, AlhuayOscar commented on src/pages/login/login.tsx
> +            !values.email.includes('@') ||
Estaria buenisimo, más que nada quise solucionar el tema de lo visual alan, Porqué ese era el problema de la card:
https://trello.com/c/PJWqccO4/174-separar-las-logicas-de-validacion-de-los-errores-en-los-inputs-del-login 
![image](https://github.com/LlibertadApp/frontend/assets/90626121/a690b76b-3736-4429-9533-351419316c5d)

2023-11-07 12:19 UTC, toro705 commented on src/pages/login/login.tsx
> +            !values.email.includes('@') ||
Hoy al mediodía estoy! Avisame si tipo 13 podes 😄

2023-11-07 18:20 UTC, AlhuayOscar commented on src/pages/login/login.tsx
> +            !values.email.includes('@') ||
Sisi ando por el Discord pero aparecia desconectado jaja

2023-11-09 00:53 UTC, closed without merging